FROM node:carbon

EXPOSE 3000

WORKDIR /app

COPY package.json package-lock*.json ./

RUN chown -R node:node .

USER node

RUN npm install && npm cache clean --force

COPY --chown=node:node . .

CMD [ "node", "app.js"]

